name:                toodles
version:             1.0.0
github:              "aviaviavi/toodles"
license:             MIT
author:              "Avi Press"
maintainer:          "mail@avi.press"
copyright:           "2018 Avi Press"
category:            Project Management

extra-source-files:
- README.md

data-files:
- web/js/app.js
- web/js/*
- web/html/*
- web/css/*
- web/fonts/*
- web/img/*

synopsis:            Manage the TODO entries in your code
description:
  >
    Toodles scrapes your entire repository for TODO entries and organizes them so
    you can manage your project directly from the code. View, filter, sort, and edit
    your TODO\'s with an easy to use web application. When you make changes via
    toodles, the edits will be applied directly the TODO entries in your code.
    When you\'re done, commit and push your changes to share them with your team!

ghc-options:
  - -Wall
  - -Wcompat

dependencies:
- base >= 4.0 && < 5

# TODO(avi) dependencies need to be relaxed and
# fixed to include other ghc versions
library:
  source-dirs: src
  exposed-modules:
  - Parse
  - Types
  - Config
  - ToodlesApi
  - Server
  dependencies:
  - hspec >= 2.4.4
  - hspec-expectations >=0.8.2
  - MissingH >=1.4.0.1
  - aeson ==1.3.1.1
  - blaze-html ==0.9.1.1
  - cmdargs ==0.10.20
  - directory ==1.3.1.5
  - megaparsec ==6.5.0
  - regex-posix ==0.95.2
  - servant ==0.14.1
  - servant-blaze ==0.8
  - servant-server ==0.14.1
  - strict ==0.3.2
  - text ==1.2.3.1
  - wai ==3.2.1.2
  - warp ==3.2.25
  - yaml ==0.8.32

executables:
  toodles:
    main:                Main.hs
    source-dirs:
    - app
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -O3
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - hspec >= 2.4.4
    - hspec-expectations >=0.8.2
    - MissingH >=1.4.0.1
    - aeson ==1.3.1.1
    - blaze-html ==0.9.1.1
    - cmdargs ==0.10.20
    - directory ==1.3.1.5
    - megaparsec ==6.5.0
    - regex-posix ==0.95.2
    - servant ==0.14.1
    - servant-blaze ==0.8
    - servant-server ==0.14.1
    - strict ==0.3.2
    - text ==1.2.3.1
    - wai ==3.2.1.2
    - warp ==3.2.25
    - yaml ==0.8.32

tests:
  toodles-test:
    main:                Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -w
    dependencies:
    - toodles
    - hspec >= 2.4.4
    - hspec-expectations >=0.8.2
    - MissingH >=1.4.0.1
    - aeson ==1.3.1.1
    - blaze-html ==0.9.1.1
    - cmdargs ==0.10.20
    - directory ==1.3.1.5
    - megaparsec ==6.5.0
    - regex-posix ==0.95.2
    - servant ==0.14.1
    - servant-blaze ==0.8
    - servant-server ==0.14.1
    - strict ==0.3.2
    - text ==1.2.3.1
    - wai ==3.2.1.2
    - warp ==3.2.25
    - yaml ==0.8.32
